[build]
builder = "nixpacks"

[deploy]
startCommand = "chainlit run app_sa.py --host 0.0.0.0 --port ${PORT:-8000}"
healthcheckPath = "/"
healthcheckTimeout = 600
numReplicas = 1
sleepApplication = false
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
